github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  version_updates:
    exclude:
      - "2-eol"
      - "py2-eol"
